-- Seed: Ganjam district post offices (India Post via data.gov.in).
-- Generated from public/ganjam_district_pincodes.csv. Re-runnable.
-- Requires migration 028 to have been applied first.

INSERT INTO ganjam_post_offices (pincode, area_name, office_type, sub_office, division) VALUES
  ('760001', 'Berhampur(GM) H.O', 'Head Office (H.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Badakhemundi Street S.O', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Bhapur Bazar S.O', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Bijipur S.O', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Brajanagar', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Gandhinagar S.O (Ganjam)', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Gatebazar S.O', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Godavarishanagar S.O', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Khallikote College S.O', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760001', 'Military Lines S.O', 'Sub Office (S.O.)', 'Berhampur(GM) H.O', 'Berhampur Division'),
  ('760002', 'Berhampur City S.O', 'Sub Office (S.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Park Street S.O', 'Sub Office (S.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Premnagar S.O (Ganjam)', 'Sub Office (S.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Sriram Nagar S.O', 'Sub Office (S.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Banthapalli B.O', 'Branch Office (B.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Bendalia B.O', 'Branch Office (B.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Dakhinpur B.O', 'Branch Office (B.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Lathi B.O', 'Branch Office (B.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Mohuda B.O', 'Branch Office (B.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760002', 'Puruna Berhampur B.O', 'Branch Office (B.O.)', 'Berhampur City S.O', 'Berhampur Division'),
  ('760003', 'Gosaninuagam S.O', 'Sub Office (S.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760003', 'Daspur B.O', 'Branch Office (B.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760003', 'Haladiapadar B.O', 'Branch Office (B.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760003', 'Keluapalli B.O', 'Branch Office (B.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760003', 'Ladigam B.O', 'Branch Office (B.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760003', 'Markandi B.O', 'Branch Office (B.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760003', 'Padmapur B.O', 'Branch Office (B.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760003', 'Phulta B.O', 'Branch Office (B.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760003', 'Rangipur B.O', 'Branch Office (B.O.)', 'Gosaninuagam S.O', 'Berhampur Division'),
  ('760004', 'Baidyanathpur S.O', 'Sub Office (S.O.)', 'Baidyanathpur S.O', 'Berhampur Division'),
  ('760004', 'Courtpeta S.O', 'Sub Office (S.O.)', 'Baidyanathpur S.O', 'Berhampur Division'),
  ('760004', 'Goilundi S.O', 'Sub Office (S.O.)', 'Baidyanathpur S.O', 'Berhampur Division'),
  ('760004', 'Medical College S.O (Ganjam)', 'Sub Office (S.O.)', 'Baidyanathpur S.O', 'Berhampur Division'),
  ('760005', 'Hillpatna S.O', 'Sub Office (S.O.)', 'Hillpatna S.O', 'Berhampur Division'),
  ('760006', 'Panigrahipentho S.O', 'Sub Office (S.O.)', 'Panigrahipentho S.O', 'Berhampur Division'),
  ('760006', 'Sankarapur S.O', 'Sub Office (S.O.)', 'Panigrahipentho S.O', 'Berhampur Division'),
  ('760007', 'Berhampur University S.O', 'Sub Office (S.O.)', 'Berhampur University S.O', 'Berhampur Division'),
  ('760007', 'Badakusasthali B.O', 'Branch Office (B.O.)', 'Berhampur University S.O', 'Berhampur Division'),
  ('760007', 'Badapur B.O', 'Branch Office (B.O.)', 'Berhampur University S.O', 'Berhampur Division'),
  ('760007', 'Bahadurpeta B.O', 'Branch Office (B.O.)', 'Berhampur University S.O', 'Berhampur Division'),
  ('760007', 'Narendrapur B.O', 'Branch Office (B.O.)', 'Berhampur University S.O', 'Berhampur Division'),
  ('760007', 'Rangailunda B.O', 'Branch Office (B.O.)', 'Berhampur University S.O', 'Berhampur Division'),
  ('760008', 'Industrial Estates S.O', 'Sub Office (S.O.)', 'Industrial Estates S.O', 'Berhampur Division'),
  ('760008', 'Lanjipalli S.O', 'Sub Office (S.O.)', 'Industrial Estates S.O', 'Berhampur Division'),
  ('760009', 'Nabeen S.O', 'Sub Office (S.O.)', 'Nabeen S.O', 'Berhampur Division'),
  ('760010', 'Engineering School S.O', 'Sub Office (S.O.)', 'Engineering School S.O', 'Berhampur Division'),
  ('760010', 'Ankuli B.O', 'Branch Office (B.O.)', 'Engineering School S.O', 'Berhampur Division'),
  ('760010', 'Dura B.O', 'Branch Office (B.O.)', 'Engineering School S.O', 'Berhampur Division'),
  ('760011', 'AMBAPUA SO', 'Sub Office (S.O.)', 'AMBAPUA SO', 'Berhampur Division'),
  ('761001', 'Nimakhandi S.O', 'Sub Office (S.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Bhabinipur B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Borigam B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Gurunthi B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Hugulapata B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Jagadalapur B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Jhadankuli B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Krupasindhupur B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Lochapada B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761001', 'Palasi B.O', 'Branch Office (B.O.)', 'Nimakhandi S.O', 'Berhampur Division'),
  ('761002', 'Gopalpur S.O (Ganjam)', 'Sub Office (S.O.)', 'Gopalpur S.O (Ganjam)', 'Berhampur Division'),
  ('761002', 'Badaputi B.O', 'Branch Office (B.O.)', 'Gopalpur S.O (Ganjam)', 'Berhampur Division'),
  ('761002', 'Boxipalli B.O', 'Branch Office (B.O.)', 'Gopalpur S.O (Ganjam)', 'Berhampur Division'),
  ('761002', 'Ganju B.O', 'Branch Office (B.O.)', 'Gopalpur S.O (Ganjam)', 'Berhampur Division'),
  ('761002', 'Kallipalli B.O', 'Branch Office (B.O.)', 'Gopalpur S.O (Ganjam)', 'Berhampur Division'),
  ('761002', 'Narayanapur B.O', 'Branch Office (B.O.)', 'Gopalpur S.O (Ganjam)', 'Berhampur Division'),
  ('761002', 'Upalaputti B.O', 'Branch Office (B.O.)', 'Gopalpur S.O (Ganjam)', 'Berhampur Division'),
  ('761002', 'Venkataraipur B.O', 'Branch Office (B.O.)', 'Gopalpur S.O (Ganjam)', 'Berhampur Division'),
  ('761003', 'Bhatakumarada S.O', 'Sub Office (S.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Baghala B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Bellagam B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Bhabandha B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Chandipadar B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Dhobadipatapur B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Gondala B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Jagannathpur B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Laxmipur B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Sahapur B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Sunathara B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761003', 'Tanganapalli B.O', 'Branch Office (B.O.)', 'Bhatakumarada S.O', 'Berhampur Division'),
  ('761004', 'Patrapur S.O', 'Sub Office (S.O.)', 'Patrapur S.O', 'Berhampur Division'),
  ('761004', 'Badabaranga B.O', 'Branch Office (B.O.)', 'Patrapur S.O', 'Berhampur Division'),
  ('761004', 'Bhimpur B.O', 'Branch Office (B.O.)', 'Patrapur S.O', 'Berhampur Division'),
  ('761004', 'Kelua B.O', 'Branch Office (B.O.)', 'Patrapur S.O', 'Berhampur Division'),
  ('761004', 'Khambarigam B.O', 'Branch Office (B.O.)', 'Patrapur S.O', 'Berhampur Division'),
  ('761004', 'Moisanpur B.O', 'Branch Office (B.O.)', 'Patrapur S.O', 'Berhampur Division'),
  ('761004', 'Samantiapalli B.O', 'Branch Office (B.O.)', 'Patrapur S.O', 'Berhampur Division'),
  ('761004', 'Santoshpur B.O', 'Branch Office (B.O.)', 'Patrapur S.O', 'Berhampur Division'),
  ('761005', 'Jaradagada S.O', 'Sub Office (S.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Ambapur B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Andanda B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Burutal B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Chikati Badapur B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Gundra B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Jarada Ankuli B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Suanakhala B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Sunareddy B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761005', 'Tumbagada B.O', 'Branch Office (B.O.)', 'Jaradagada S.O', 'Berhampur Division'),
  ('761006', 'Jayantipur S.O', 'Sub Office (S.O.)', 'Jayantipur S.O', 'Berhampur Division'),
  ('761006', 'B.Nuagam B.O', 'Branch Office (B.O.)', 'Jayantipur S.O', 'Berhampur Division'),
  ('761006', 'Bansola B.O', 'Branch Office (B.O.)', 'Jayantipur S.O', 'Berhampur Division'),
  ('761006', 'Barango B.O', 'Branch Office (B.O.)', 'Jayantipur S.O', 'Berhampur Division'),
  ('761006', 'Gudipadar B.O', 'Branch Office (B.O.)', 'Jayantipur S.O', 'Berhampur Division'),
  ('761006', 'Kesaripada B.O', 'Branch Office (B.O.)', 'Jayantipur S.O', 'Berhampur Division'),
  ('761006', 'Totipuram B.O', 'Branch Office (B.O.)', 'Jayantipur S.O', 'Berhampur Division'),
  ('761007', 'Padmanavapur S.O', 'Sub Office (S.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'B.Turubudi B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Boripadar B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Chaitanyapur B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Golanda B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Guhalpur B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Jharipadar B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Kaithkhandi B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Narendrappur B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Odasingi B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761007', 'Talasingi B.O', 'Branch Office (B.O.)', 'Padmanavapur S.O', 'Berhampur Division'),
  ('761008', 'Golanthara S.O', 'Sub Office (S.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Kanisi Hat S.O.', 'Sub Office (S.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Biswanathpur B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Chikarada B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Govindanagar B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Indrakhi B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Konika B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Konisi B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Kotharasingi B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Mantridi B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Mendrajpur B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Panchama B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Rondha B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Sasanapadar B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Shiala B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761008', 'Sunadei B.O', 'Branch Office (B.O.)', 'Golanthara S.O', 'Berhampur Division'),
  ('761009', 'Girisola S.O', 'Sub Office (S.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761009', 'Gopinathpur B.O', 'Branch Office (B.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761009', 'Haripur B.O', 'Branch Office (B.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761009', 'Jhatipadar B.O', 'Branch Office (B.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761009', 'Kaviti Suvani B.O', 'Branch Office (B.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761009', 'Koturu B.O', 'Branch Office (B.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761009', 'R.Suvani B.O', 'Branch Office (B.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761009', 'Sonepur B.O', 'Branch Office (B.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761009', 'Surala B.O', 'Branch Office (B.O.)', 'Girisola S.O', 'Berhampur Division'),
  ('761010', 'Chikiti S.O', 'Sub Office (S.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Badapalanka B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Chikitipentho B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Jagamohanapur B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Kalabada B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Kolathia B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Kottilingi B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Krushanapur B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Madhabandha B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Nuagaon B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Pitatoli B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Ramchandrapur B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761010', 'Rampa B.O', 'Branch Office (B.O.)', 'Chikiti S.O', 'Berhampur Division'),
  ('761011', 'Nuapada S.O', 'Sub Office (S.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761011', 'B.L.N.Pur B.O', 'Branch Office (B.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761011', 'Badakhajahari B.O', 'Branch Office (B.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761011', 'Banamali B.O', 'Branch Office (B.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761011', 'Dabarsingi B.O', 'Branch Office (B.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761011', 'Dauni B.O', 'Branch Office (B.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761011', 'Godagovindapur B.O', 'Branch Office (B.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761011', 'Goudagam B.O', 'Branch Office (B.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761011', 'L.N.Pur B.O', 'Branch Office (B.O.)', 'Nuapada S.O', 'Berhampur Division'),
  ('761012', 'Digapahandi S.O', 'Sub Office (S.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761012', 'Digapahandi Tahasil Colony S.O', 'Sub Office (S.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761012', 'Ambagaon B.O', 'Branch Office (B.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761012', 'Ankorada B.O', 'Branch Office (B.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761012', 'Chudangapur B.O', 'Branch Office (B.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761012', 'Gokarnapur B.O', 'Branch Office (B.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761012', 'Kusapada B.O', 'Branch Office (B.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761012', 'Maulabhanja B.O', 'Branch Office (B.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761012', 'Sahaspur B.O', 'Branch Office (B.O.)', 'Digapahandi S.O', 'Berhampur Division'),
  ('761013', 'Pattapur S.O', 'Sub Office (S.O.)', 'Pattapur S.O', 'Aska Division'),
  ('761013', 'Erendra B.O', 'Branch Office (B.O.)', 'Pattapur S.O', 'Aska Division'),
  ('761013', 'Gangapur B.O', 'Branch Office (B.O.)', 'Pattapur S.O', 'Aska Division'),
  ('761013', 'J.Balabhadrapur B.O', 'Branch Office (B.O.)', 'Pattapur S.O', 'Aska Division'),
  ('761013', 'Khallingi B.O', 'Branch Office (B.O.)', 'Pattapur S.O', 'Aska Division'),
  ('761013', 'Mahanala B.O', 'Branch Office (B.O.)', 'Pattapur S.O', 'Aska Division'),
  ('761013', 'P.Jagannathpur B.O', 'Branch Office (B.O.)', 'Pattapur S.O', 'Aska Division'),
  ('761013', 'P.Ramachandrapur B.O', 'Branch Office (B.O.)', 'Pattapur S.O', 'Aska Division'),
  ('761014', 'Pudamari S.O', 'Sub Office (S.O.)', 'Pudamari S.O', 'Berhampur Division'),
  ('761014', 'Chanamari B.O', 'Branch Office (B.O.)', 'Pudamari S.O', 'Berhampur Division'),
  ('761014', 'Kansamari B.O', 'Branch Office (B.O.)', 'Pudamari S.O', 'Berhampur Division'),
  ('761014', 'P.Govindapur B.O', 'Branch Office (B.O.)', 'Pudamari S.O', 'Berhampur Division'),
  ('761014', 'Patiguda B.O', 'Branch Office (B.O.)', 'Pudamari S.O', 'Berhampur Division'),
  ('761014', 'Singipur B.O', 'Branch Office (B.O.)', 'Pudamari S.O', 'Berhampur Division'),
  ('761018', 'Purushottampur S.O', 'Sub Office (S.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Badabaragam B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Chingudighai B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Gnagadahani B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Hottapur B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Jamuni B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Kinigam B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Purushottampur Nbs B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Ranajhali B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Sikula B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Soma B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761018', 'Taratrini Hills B.O', 'Branch Office (B.O.)', 'Purushottampur S.O', 'Berhampur Division'),
  ('761019', 'Pratapur S.O (Ganjam)', 'Sub Office (S.O.)', 'Pratapur S.O (Ganjam)', 'Berhampur Division'),
  ('761019', 'Alladigam B.O', 'Branch Office (B.O.)', 'Pratapur S.O (Ganjam)', 'Berhampur Division'),
  ('761019', 'Badachakada B.O', 'Branch Office (B.O.)', 'Pratapur S.O (Ganjam)', 'Berhampur Division'),
  ('761019', 'Badarampalli B.O', 'Branch Office (B.O.)', 'Pratapur S.O (Ganjam)', 'Berhampur Division'),
  ('761019', 'Khajipalli B.O', 'Branch Office (B.O.)', 'Pratapur S.O (Ganjam)', 'Berhampur Division'),
  ('761019', 'Komanda B.O', 'Branch Office (B.O.)', 'Pratapur S.O (Ganjam)', 'Berhampur Division'),
  ('761019', 'Poirasi B.O', 'Branch Office (B.O.)', 'Pratapur S.O (Ganjam)', 'Berhampur Division'),
  ('761020', 'Chatrapur H.O', 'Head Office (H.O.)', 'Chatrapur H.O', 'Berhampur Division'),
  ('761020', 'Chatrapur Bazar S.O', 'Sub Office (S.O.)', 'Chatrapur H.O', 'Berhampur Division'),
  ('761020', 'Sitarampalli S.O', 'Sub Office (S.O.)', 'Chatrapur H.O', 'Berhampur Division'),
  ('761025', 'Jayashree S.O', 'Sub Office (S.O.)', 'Jayashree S.O', 'Berhampur Division'),
  ('761026', 'Ganjam S.O', 'Sub Office (S.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Agastinuagam B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Badamadhapur B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Baulagam B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Bupilingi B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Chikalakhandi B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Humuri B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Kalyanapur B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Karapada B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Karatoli B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Mahanadapur B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Municipentho B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Pallibandha B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Podapadar B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Pottalmpur B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Rajpur B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Rukunigam B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761026', 'Sarabhimpur B.O', 'Branch Office (B.O.)', 'Ganjam S.O', 'Berhampur Division'),
  ('761027', 'Humma S.O', 'Sub Office (S.O.)', 'Humma S.O', 'Berhampur Division'),
  ('761027', 'Haripur Burudi B.O', 'Branch Office (B.O.)', 'Humma S.O', 'Berhampur Division'),
  ('761027', 'Mallada B.O', 'Branch Office (B.O.)', 'Humma S.O', 'Berhampur Division'),
  ('761027', 'Palur B.O', 'Branch Office (B.O.)', 'Humma S.O', 'Berhampur Division'),
  ('761027', 'Santoshpur B.O', 'Branch Office (B.O.)', 'Humma S.O', 'Berhampur Division'),
  ('761028', 'Minchinipatana S.O', 'Sub Office (S.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Rambha S.O', 'Sub Office (S.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Biruligada B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Dimiria B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Golagandapalli B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Kanaka B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Khandadeuli B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Madhuruchua B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Paladhuapalli B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Polango B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761028', 'Sabulia B.O', 'Branch Office (B.O.)', 'Minchinipatana S.O', 'Berhampur Division'),
  ('761029', 'Khallikote RS S.O', 'Sub Office (S.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Aitipur B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Badapalli B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Bhejiput B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Bhikapada B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Bikrampur B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Khajapalli B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Koirasi B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Konheipur B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Langaleswar B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Panditgam B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Pathara B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761029', 'Tentuliapalli B.O', 'Branch Office (B.O.)', 'Khallikote RS S.O', 'Berhampur Division'),
  ('761030', 'Khallikote S.O', 'Sub Office (S.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Badhinuapalli B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Balunkeswarapur B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Bania B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Barasara B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Chikili B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Kendupata B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Kushadhipa B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Mathura B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Syamsundarpur B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761030', 'Talapada B.O', 'Branch Office (B.O.)', 'Khallikote S.O', 'Berhampur Division'),
  ('761031', 'Beguniapada S.O', 'Sub Office (S.O.)', 'Beguniapada S.O', 'Berhampur Division'),
  ('761031', 'Biribatia B.O', 'Branch Office (B.O.)', 'Beguniapada S.O', 'Berhampur Division'),
  ('761031', 'Borida B.O', 'Branch Office (B.O.)', 'Beguniapada S.O', 'Berhampur Division'),
  ('761031', 'Kanchana B.O', 'Branch Office (B.O.)', 'Beguniapada S.O', 'Berhampur Division'),
  ('761031', 'Naikanipalli B.O', 'Branch Office (B.O.)', 'Beguniapada S.O', 'Berhampur Division'),
  ('761031', 'Pustapur B.O', 'Branch Office (B.O.)', 'Beguniapada S.O', 'Berhampur Division'),
  ('761031', 'Saurachachina B.O', 'Branch Office (B.O.)', 'Beguniapada S.O', 'Berhampur Division'),
  ('761031', 'Tirida B.O', 'Branch Office (B.O.)', 'Beguniapada S.O', 'Berhampur Division'),
  ('761032', 'Kodala S.O', 'Sub Office (S.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Kodala Tahasil Colony S.O', 'Sub Office (S.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'B.L.N.Pur B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Beruanbadi B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Chingudikhola B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Danapur B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Digapada B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Gouradeipur B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Jagilipadar B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Kodala Bus Stand B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Mardakote B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Mardamekha B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Mathasarasingi B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Mundala B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761032', 'Phasi B.O', 'Branch Office (B.O.)', 'Kodala S.O', 'Berhampur Division'),
  ('761035', 'Sumandala S.O', 'Sub Office (S.O.)', 'Sumandala S.O', 'Berhampur Division'),
  ('761035', 'Angaragam B.O', 'Branch Office (B.O.)', 'Sumandala S.O', 'Berhampur Division'),
  ('761035', 'Badakhairakhama B.O', 'Branch Office (B.O.)', 'Sumandala S.O', 'Berhampur Division'),
  ('761035', 'Burujhuri Nuagam B.O', 'Branch Office (B.O.)', 'Sumandala S.O', 'Berhampur Division'),
  ('761035', 'Kumaripari B.O', 'Branch Office (B.O.)', 'Sumandala S.O', 'Berhampur Division'),
  ('761035', 'Sandhamula B.O', 'Branch Office (B.O.)', 'Sumandala S.O', 'Berhampur Division'),
  ('761035', 'Sankuda B.O', 'Branch Office (B.O.)', 'Sumandala S.O', 'Berhampur Division'),
  ('761035', 'Talasara B.O', 'Branch Office (B.O.)', 'Sumandala S.O', 'Berhampur Division'),
  ('761037', 'Surangi S.O', 'Sub Office (S.O.)', 'Surangi S.O', 'Berhampur Division'),
  ('761037', 'Gothagam B.O', 'Branch Office (B.O.)', 'Surangi S.O', 'Berhampur Division'),
  ('761037', 'Kharnipada B.O', 'Branch Office (B.O.)', 'Surangi S.O', 'Berhampur Division'),
  ('761037', 'Nuapentho B.O', 'Branch Office (B.O.)', 'Surangi S.O', 'Berhampur Division'),
  ('761037', 'Padadigi B.O', 'Branch Office (B.O.)', 'Surangi S.O', 'Berhampur Division'),
  ('761037', 'S.B.Pentho B.O', 'Branch Office (B.O.)', 'Surangi S.O', 'Berhampur Division'),
  ('761037', 'Tandipur B.O', 'Branch Office (B.O.)', 'Surangi S.O', 'Berhampur Division'),
  ('761041', 'Badakharida S.O', 'Sub Office (S.O.)', 'Badakharida S.O', 'Berhampur Division'),
  ('761041', 'Arakhapur B.O', 'Branch Office (B.O.)', 'Badakharida S.O', 'Berhampur Division'),
  ('761041', 'Badamahuri B.O', 'Branch Office (B.O.)', 'Badakharida S.O', 'Berhampur Division'),
  ('761041', 'Bhutsarasingi B.O', 'Branch Office (B.O.)', 'Badakharida S.O', 'Berhampur Division'),
  ('761041', 'Rama Sanarayanpur B.O', 'Branch Office (B.O.)', 'Badakharida S.O', 'Berhampur Division'),
  ('761042', 'Bomokei S.O', 'Sub Office (S.O.)', 'Bomokei S.O', 'Berhampur Division'),
  ('761042', 'Badadumbala B.O', 'Branch Office (B.O.)', 'Bomokei S.O', 'Berhampur Division'),
  ('761042', 'Ballijodi B.O', 'Branch Office (B.O.)', 'Bomokei S.O', 'Berhampur Division'),
  ('761042', 'Dekahli B.O', 'Branch Office (B.O.)', 'Bomokei S.O', 'Berhampur Division'),
  ('761042', 'Jaccaro B.O', 'Branch Office (B.O.)', 'Bomokei S.O', 'Berhampur Division'),
  ('761042', 'Karapada B.O', 'Branch Office (B.O.)', 'Bomokei S.O', 'Berhampur Division'),
  ('761042', 'Manikyapur B.O', 'Branch Office (B.O.)', 'Bomokei S.O', 'Berhampur Division'),
  ('761042', 'Mundapata B.O', 'Branch Office (B.O.)', 'Bomokei S.O', 'Berhampur Division'),
  ('761043', 'Pandia S.O', 'Sub Office (S.O.)', 'Pandia S.O', 'Berhampur Division'),
  ('761043', 'Antarigam B.O', 'Branch Office (B.O.)', 'Pandia S.O', 'Berhampur Division'),
  ('761043', 'Chatamundali B.O', 'Branch Office (B.O.)', 'Pandia S.O', 'Berhampur Division'),
  ('761043', 'Kalidaspur B.O', 'Branch Office (B.O.)', 'Pandia S.O', 'Berhampur Division'),
  ('761043', 'Morabai B.O', 'Branch Office (B.O.)', 'Pandia S.O', 'Berhampur Division'),
  ('761043', 'Pandarakhalli B.O', 'Branch Office (B.O.)', 'Pandia S.O', 'Berhampur Division'),
  ('761045', 'Matikhalo S.O', 'Sub Office (S.O.)', 'Matikhalo S.O', 'Berhampur Division'),
  ('761045', 'Bada Aryapalli B.O', 'Branch Office (B.O.)', 'Matikhalo S.O', 'Berhampur Division'),
  ('761045', 'Banabulapalli B.O', 'Branch Office (B.O.)', 'Matikhalo S.O', 'Berhampur Division'),
  ('761045', 'Bhikaripalli B.O', 'Branch Office (B.O.)', 'Matikhalo S.O', 'Berhampur Division'),
  ('761045', 'Chamakhandi B.O', 'Branch Office (B.O.)', 'Matikhalo S.O', 'Berhampur Division'),
  ('761045', 'Kanamana B.O', 'Branch Office (B.O.)', 'Matikhalo S.O', 'Berhampur Division'),
  ('761045', 'Sindurapur B.O', 'Branch Office (B.O.)', 'Matikhalo S.O', 'Berhampur Division'),
  ('761045', 'Sriramchandrapur B.O', 'Branch Office (B.O.)', 'Matikhalo S.O', 'Berhampur Division'),
  ('761052', 'Golabandha S.O', 'Sub Office (S.O.)', 'Golabandha S.O', 'Berhampur Division'),
  ('761054', 'Ballipada S.O', 'Sub Office (S.O.)', 'Ballipada S.O', 'Berhampur Division'),
  ('761054', 'Badiosta B.O', 'Branch Office (B.O.)', 'Ballipada S.O', 'Berhampur Division'),
  ('761054', 'Dengapadar B.O', 'Branch Office (B.O.)', 'Ballipada S.O', 'Berhampur Division'),
  ('761054', 'Goutami B.O', 'Branch Office (B.O.)', 'Ballipada S.O', 'Berhampur Division'),
  ('761054', 'Nalihada B.O', 'Branch Office (B.O.)', 'Ballipada S.O', 'Berhampur Division'),
  ('761054', 'Sidheswara B.O', 'Branch Office (B.O.)', 'Ballipada S.O', 'Berhampur Division'),
  ('761055', 'Bissmagiri S.O', 'Sub Office (S.O.)', 'Bissmagiri S.O', 'Berhampur Division'),
  ('761055', 'Baritola B.O', 'Branch Office (B.O.)', 'Bissmagiri S.O', 'Berhampur Division'),
  ('761055', 'Gadasamantarapur B.O', 'Branch Office (B.O.)', 'Bissmagiri S.O', 'Berhampur Division'),
  ('761055', 'Khamarigam B.O', 'Branch Office (B.O.)', 'Bissmagiri S.O', 'Berhampur Division'),
  ('761055', 'Nimakhandi Pentho B.O', 'Branch Office (B.O.)', 'Bissmagiri S.O', 'Berhampur Division'),
  ('761055', 'Panada B.O', 'Branch Office (B.O.)', 'Bissmagiri S.O', 'Berhampur Division'),
  ('761055', 'Phasiguda B.O', 'Branch Office (B.O.)', 'Bissmagiri S.O', 'Berhampur Division'),
  ('761055', 'Sahadev Tikirapada B.O', 'Branch Office (B.O.)', 'Bissmagiri S.O', 'Berhampur Division'),
  ('761100', 'Kukudakhandi S.O', 'Sub Office (S.O.)', 'Kukudakhandi S.O', 'Berhampur Division'),
  ('761100', 'Ankushpur B.O', 'Branch Office (B.O.)', 'Kukudakhandi S.O', 'Berhampur Division'),
  ('761100', 'Baulojholi B.O', 'Branch Office (B.O.)', 'Kukudakhandi S.O', 'Berhampur Division'),
  ('761100', 'Dayapalli B.O', 'Branch Office (B.O.)', 'Kukudakhandi S.O', 'Berhampur Division'),
  ('761100', 'Gopinathpur B.O', 'Branch Office (B.O.)', 'Kukudakhandi S.O', 'Berhampur Division'),
  ('761100', 'Ollarigada B.O', 'Branch Office (B.O.)', 'Kukudakhandi S.O', 'Berhampur Division'),
  ('761100', 'Raijhola B.O', 'Branch Office (B.O.)', 'Kukudakhandi S.O', 'Berhampur Division'),
  ('761100', 'Satapahandia B.O', 'Branch Office (B.O.)', 'Kukudakhandi S.O', 'Berhampur Division'),
  ('761101', 'Kanchuru S.O', 'Sub Office (S.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761101', 'Badakhandi B.O', 'Branch Office (B.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761101', 'Durabandha B.O', 'Branch Office (B.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761101', 'Makarjhola B.O', 'Branch Office (B.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761101', 'P.Padmanabhapur B.O', 'Branch Office (B.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761101', 'S.Ambagam B.O', 'Branch Office (B.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761101', 'Samarjhola B.O', 'Branch Office (B.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761101', 'Sapuapalli B.O', 'Branch Office (B.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761101', 'Saru B.O', 'Branch Office (B.O.)', 'Kanchuru S.O', 'Aska Division'),
  ('761102', 'Hinjilicut S.O', 'Sub Office (S.O.)', 'Hinjilicut S.O', 'Aska Division'),
  ('761102', 'Hinjlicut College Road S.O', 'Sub Office (S.O.)', 'Hinjilicut S.O', 'Aska Division'),
  ('761102', 'Chandulli B.O', 'Branch Office (B.O.)', 'Hinjilicut S.O', 'Aska Division'),
  ('761102', 'Kharida B.O', 'Branch Office (B.O.)', 'Hinjilicut S.O', 'Aska Division'),
  ('761102', 'Nandiko B.O', 'Branch Office (B.O.)', 'Hinjilicut S.O', 'Aska Division'),
  ('761102', 'Putiapadar B.O', 'Branch Office (B.O.)', 'Hinjilicut S.O', 'Aska Division'),
  ('761102', 'Ralaba B.O', 'Branch Office (B.O.)', 'Hinjilicut S.O', 'Aska Division'),
  ('761102', 'Sikiri B.O', 'Branch Office (B.O.)', 'Hinjilicut S.O', 'Aska Division'),
  ('761103', 'Pitala S.O', 'Sub Office (S.O.)', 'Pitala S.O', 'Aska Division'),
  ('761103', 'Brahmanchhai B.O', 'Branch Office (B.O.)', 'Pitala S.O', 'Aska Division'),
  ('761103', 'Mahachhai B.O', 'Branch Office (B.O.)', 'Pitala S.O', 'Aska Division'),
  ('761103', 'Narendrapur B.O', 'Branch Office (B.O.)', 'Pitala S.O', 'Aska Division'),
  ('761103', 'Podingi B.O', 'Branch Office (B.O.)', 'Pitala S.O', 'Aska Division'),
  ('761103', 'Ramachandrapur B.O', 'Branch Office (B.O.)', 'Pitala S.O', 'Aska Division'),
  ('761103', 'Tanhara B.O', 'Branch Office (B.O.)', 'Pitala S.O', 'Aska Division'),
  ('761103', 'Tankachhai B.O', 'Branch Office (B.O.)', 'Pitala S.O', 'Aska Division'),
  ('761104', 'Banadevi Patna S.O', 'Sub Office (S.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Gopinath Patna S.O', 'Sub Office (S.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Kabisuryanagar S.O', 'Sub Office (S.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Ambapua B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'B.Nuapalli B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Baliasara B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Barida B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Bolosara B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Gangapur B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Ghodapolan B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Gudiali B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Hindola B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Jarada B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Jhadabai B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Paikajamuna B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Pathara B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Sialia B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Sunapalli B.O', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761104', 'Sunarijhola BO', 'Branch Office (B.O.)', 'Banadevi Patna S.O', 'Aska Division'),
  ('761105', 'Polosara S.O', 'Sub Office (S.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Athagadapatna B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Banthapalli B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Bellagam B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Bhabarada B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Budhamba B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Chirakipadasasan B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Gochabadi B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Jakara B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Kalambo B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Khanduru B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Madhupalli B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Mathura B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Pandiripada B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Polasara Nimina B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761105', 'Tentulia B.O', 'Branch Office (B.O.)', 'Polosara S.O', 'Berhampur Division'),
  ('761106', 'Seragada S.O', 'Sub Office (S.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Bandhaguda B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Baramundalli B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Dasamundali B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Dhabalpur B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Dhanantara B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'K.Karadakana B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Kachakhandi B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Kullagada B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Kumarpani B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Mahupadar B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'S.Gopalpur B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761106', 'Takarada B.O', 'Branch Office (B.O.)', 'Seragada S.O', 'Aska Division'),
  ('761107', 'Dharakote S.O', 'Sub Office (S.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Baharpur B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Baradabilli B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Bethuara B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'D.Singipur B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'G.D.Palli B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Jahada B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Janibilli B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Manikyapur B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Nuagada B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Rugumu B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Saba B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761107', 'Suramani B.O', 'Branch Office (B.O.)', 'Dharakote S.O', 'Aska Division'),
  ('761108', 'Surada S.O', 'Sub Office (S.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Amrutulu B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'B.Kotibadi B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Badabadangi B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Genja B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Gopalpursasan B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Hukuma B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'K.Jatabadi B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Lathipada B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Palakatu B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Ratnapur B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Sarabadi B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Sorisbilli B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761108', 'Surada Bazar B.O', 'Branch Office (B.O.)', 'Surada S.O', 'Aska Division'),
  ('761109', 'Badagada S.O', 'Sub Office (S.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Balarampur B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Borada B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Ekalpur B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Gangapur B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Gaudagotha B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Merikote B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Padmapur B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Rai Bandha B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Sandhikendu B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761109', 'Sidhapur B.O', 'Branch Office (B.O.)', 'Badagada S.O', 'Aska Division'),
  ('761110', 'Aska H.O', 'Head Office (H.O.)', 'Aska H.O', 'Aska Division'),
  ('761110', 'Aska Junction S.O', 'Sub Office (S.O.)', 'Aska H.O', 'Aska Division'),
  ('761110', 'Khambeswari Patna S.O', 'Sub Office (S.O.)', 'Aska H.O', 'Aska Division'),
  ('761110', 'Raghunath Nagar S.O (Ganjam)', 'Sub Office (S.O.)', 'Aska H.O', 'Aska Division'),
  ('761110', 'Sunambo Street S.O', 'Sub Office (S.O.)', 'Aska H.O', 'Aska Division'),
  ('761110', 'T.O.Road S.O', 'Sub Office (S.O.)', 'Aska H.O', 'Aska Division'),
  ('761111', 'Aska College Square S.O', 'Sub Office (S.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Nuagam S.O', 'Sub Office (S.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'A.K.Deuli B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Alipur B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Babanpur B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Balichhai B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Baragam B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Dhaugam B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'G.D.Palli B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Haridapadar B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Humuki B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Jayapur B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Kalasandhapur B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Kaniary B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Kharia B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Kotinada B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Kumbhari B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Nalabanta B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761111', 'Subalaya B.O', 'Branch Office (B.O.)', 'Aska College Square S.O', 'Aska Division'),
  ('761114', 'Mundamarai S.O', 'Sub Office (S.O.)', 'Mundamarai S.O', 'Aska Division'),
  ('761114', 'Badula B.O', 'Branch Office (B.O.)', 'Mundamarai S.O', 'Aska Division'),
  ('761114', 'Jagamohan B.O', 'Branch Office (B.O.)', 'Mundamarai S.O', 'Aska Division'),
  ('761114', 'Jhadabandha B.O', 'Branch Office (B.O.)', 'Mundamarai S.O', 'Aska Division'),
  ('761114', 'Jharapari B.O', 'Branch Office (B.O.)', 'Mundamarai S.O', 'Aska Division'),
  ('761114', 'Kusuraba B.O', 'Branch Office (B.O.)', 'Mundamarai S.O', 'Aska Division'),
  ('761115', 'Gunthapada S.O', 'Sub Office (S.O.)', 'Gunthapada S.O', 'Aska Division'),
  ('761115', 'Balisira B.O', 'Branch Office (B.O.)', 'Gunthapada S.O', 'Aska Division'),
  ('761115', 'Debabhumi B.O', 'Branch Office (B.O.)', 'Gunthapada S.O', 'Aska Division'),
  ('761115', 'Mangalpur B.O', 'Branch Office (B.O.)', 'Gunthapada S.O', 'Aska Division'),
  ('761115', 'Sahaspur B.O', 'Branch Office (B.O.)', 'Gunthapada S.O', 'Aska Division'),
  ('761116', 'Bhetonoi S.O', 'Sub Office (S.O.)', 'Bhetonoi S.O', 'Aska Division'),
  ('761116', 'Badakholi B.O', 'Branch Office (B.O.)', 'Bhetonoi S.O', 'Aska Division'),
  ('761116', 'Dhaninja B.O', 'Branch Office (B.O.)', 'Bhetonoi S.O', 'Aska Division'),
  ('761116', 'Pandiapathara B.O', 'Branch Office (B.O.)', 'Bhetonoi S.O', 'Aska Division'),
  ('761116', 'Sidhanoi B.O', 'Branch Office (B.O.)', 'Bhetonoi S.O', 'Aska Division'),
  ('761117', 'Ballipadar S.O', 'Sub Office (S.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Antarapada B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Arakhapur B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Bhatakhali B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Bishnuchakra B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Gahangu B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Hatiota B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Karadabadi (A) B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Mandar B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Mangalpur B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761117', 'Rumagada B.O', 'Branch Office (B.O.)', 'Ballipadar S.O', 'Aska Division'),
  ('761118', 'Buguda S.O', 'Sub Office (S.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Adipur B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'B.Pankalbadi B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Betarasingi B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Bhamsyali B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Dhunkapada B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Gaudiabarada B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Golabandha B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Golamundala B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Golia B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Kanachhai B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Kanasukha B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Kholakhalli B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Manitara B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Motabadi B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Pangidi B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Sankuru B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761118', 'Sodak B.O', 'Branch Office (B.O.)', 'Buguda S.O', 'Aska Division'),
  ('761119', 'B D Sahi Bellagunhta S.O', 'Sub Office (S.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Bellaguntha S.O', 'Sub Office (S.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Ambapua B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'B.L.S.Pur B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Bonka B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Kirapalli B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Kudutei B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Pantikhari B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Patrapalli B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Pratapur B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761119', 'Udhra B.O', 'Branch Office (B.O.)', 'B D Sahi Bellagunhta S.O', 'Aska Division'),
  ('761120', 'Baragam S.O', 'Sub Office (S.O.)', 'Baragam S.O', 'Aska Division'),
  ('761120', 'Aladi B.O', 'Branch Office (B.O.)', 'Baragam S.O', 'Aska Division'),
  ('761120', 'B.D.Pur B.O', 'Branch Office (B.O.)', 'Baragam S.O', 'Aska Division'),
  ('761120', 'Jhadabhumi B.O', 'Branch Office (B.O.)', 'Baragam S.O', 'Aska Division'),
  ('761120', 'Khamarpalli B.O', 'Branch Office (B.O.)', 'Baragam S.O', 'Aska Division'),
  ('761120', 'Nimapadar B.O', 'Branch Office (B.O.)', 'Baragam S.O', 'Aska Division'),
  ('761120', 'Patadhar B.O', 'Branch Office (B.O.)', 'Baragam S.O', 'Aska Division'),
  ('761121', 'Jagannath Prasad S.O', 'Sub Office (S.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Alasuguma B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Chamunda B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Gandadhara B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Kadapada B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Kadua B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Kumpapada B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Kumundi B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Panchabhuti B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Rauti B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761121', 'Samarbandha B.O', 'Branch Office (B.O.)', 'Jagannath Prasad S.O', 'Aska Division'),
  ('761122', 'Nimina S.O', 'Sub Office (S.O.)', 'Nimina S.O', 'Aska Division'),
  ('761122', 'Benapata B.O', 'Branch Office (B.O.)', 'Nimina S.O', 'Aska Division'),
  ('761122', 'Kamagada B.O', 'Branch Office (B.O.)', 'Nimina S.O', 'Aska Division'),
  ('761122', 'Kendupadar B.O', 'Branch Office (B.O.)', 'Nimina S.O', 'Aska Division'),
  ('761122', 'Landajuali B.O', 'Branch Office (B.O.)', 'Nimina S.O', 'Aska Division'),
  ('761122', 'Munigadi B.O', 'Branch Office (B.O.)', 'Nimina S.O', 'Aska Division'),
  ('761123', 'Gangapur (Ganjam) S.O', 'Sub Office (S.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761123', 'Bangarada B.O', 'Branch Office (B.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761123', 'Bori B.O', 'Branch Office (B.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761123', 'K.Nuagada B.O', 'Branch Office (B.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761123', 'Khairaputi B.O', 'Branch Office (B.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761123', 'Khetribarapur B.O', 'Branch Office (B.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761123', 'Nunipadasasan B.O', 'Branch Office (B.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761123', 'Pailipada B.O', 'Branch Office (B.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761123', 'Palakasandha B.O', 'Branch Office (B.O.)', 'Gangapur (Ganjam) S.O', 'Aska Division'),
  ('761124', 'Gobara S.O', 'Sub Office (S.O.)', 'Gobara S.O', 'Aska Division'),
  ('761124', 'Badaborasingi B.O', 'Branch Office (B.O.)', 'Gobara S.O', 'Aska Division'),
  ('761124', 'Badapada B.O', 'Branch Office (B.O.)', 'Gobara S.O', 'Aska Division'),
  ('761124', 'Benipalli B.O', 'Branch Office (B.O.)', 'Gobara S.O', 'Aska Division'),
  ('761124', 'G.Dengapadar B.O', 'Branch Office (B.O.)', 'Gobara S.O', 'Aska Division'),
  ('761124', 'Kaliaguda B.O', 'Branch Office (B.O.)', 'Gobara S.O', 'Aska Division'),
  ('761124', 'Kullangi B.O', 'Branch Office (B.O.)', 'Gobara S.O', 'Aska Division'),
  ('761124', 'Madhabarida B.O', 'Branch Office (B.O.)', 'Gobara S.O', 'Aska Division'),
  ('761124', 'Nettanga B.O', 'Branch Office (B.O.)', 'Gobara S.O', 'Aska Division'),
  ('761125', 'Badakodanda S.O', 'Sub Office (S.O.)', 'Badakodanda S.O', 'Aska Division'),
  ('761125', 'Bahadapadar B.O', 'Branch Office (B.O.)', 'Badakodanda S.O', 'Aska Division'),
  ('761125', 'Dumakumpa B.O', 'Branch Office (B.O.)', 'Badakodanda S.O', 'Aska Division'),
  ('761125', 'Khamaredi B.O', 'Branch Office (B.O.)', 'Badakodanda S.O', 'Aska Division'),
  ('761125', 'Lalsingh B.O', 'Branch Office (B.O.)', 'Badakodanda S.O', 'Aska Division'),
  ('761125', 'Sanakodanda B.O', 'Branch Office (B.O.)', 'Badakodanda S.O', 'Aska Division'),
  ('761126', 'Bhanjanagar H.O', 'Head Office (H.O.)', 'Bhanjanagar H.O', 'Aska Division'),
  ('761126', 'Bhanjamargo S.O', 'Sub Office (S.O.)', 'Bhanjanagar H.O', 'Aska Division'),
  ('761126', 'Bhanjanagar  College S.O', 'Sub Office (S.O.)', 'Bhanjanagar H.O', 'Aska Division'),
  ('761126', 'Bhanjanagar Bazar S.O', 'Sub Office (S.O.)', 'Bhanjanagar H.O', 'Aska Division'),
  ('761126', 'Bhejiput S.O', 'Sub Office (S.O.)', 'Bhanjanagar H.O', 'Aska Division'),
  ('761131', 'Kullada S.O', 'Sub Office (S.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Baaruda B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Baliapata B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Balisahi B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Dholapita B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Gayaganda B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Gerada B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Golapada B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Guzurali B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Kalingapadar B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Khetamundali B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Kokolamba B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Lembhai B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Masabadi B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Rudhapadar B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Tarasinghi B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Tholadi B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Tilisinghi B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761131', 'Turumu B.O', 'Branch Office (B.O.)', 'Kullada S.O', 'Aska Division'),
  ('761132', 'Mujjagada S.O', 'Sub Office (S.O.)', 'Mujjagada S.O', 'Aska Division'),
  ('761132', 'Birikote B.O', 'Branch Office (B.O.)', 'Mujjagada S.O', 'Aska Division'),
  ('761132', 'Brhamanapadar B.O', 'Branch Office (B.O.)', 'Mujjagada S.O', 'Aska Division'),
  ('761132', 'Buduli B.O', 'Branch Office (B.O.)', 'Mujjagada S.O', 'Aska Division'),
  ('761132', 'Dadarlunda B.O', 'Branch Office (B.O.)', 'Mujjagada S.O', 'Aska Division'),
  ('761132', 'G.Rambha B.O', 'Branch Office (B.O.)', 'Mujjagada S.O', 'Aska Division'),
  ('761132', 'Gundribadi B.O', 'Branch Office (B.O.)', 'Mujjagada S.O', 'Aska Division'),
  ('761132', 'Mohaguda B.O', 'Branch Office (B.O.)', 'Mujjagada S.O', 'Aska Division'),
  ('761133', 'Jillundi S.O', 'Sub Office (S.O.)', 'Jillundi S.O', 'Aska Division'),
  ('761133', 'Baunsalundi B.O', 'Branch Office (B.O.)', 'Jillundi S.O', 'Aska Division'),
  ('761133', 'Dubuduba B.O', 'Branch Office (B.O.)', 'Jillundi S.O', 'Aska Division'),
  ('761133', 'Gamundi B.O', 'Branch Office (B.O.)', 'Jillundi S.O', 'Aska Division'),
  ('761133', 'Malaspadar B.O', 'Branch Office (B.O.)', 'Jillundi S.O', 'Aska Division'),
  ('761140', 'Tanarada S.O', 'Sub Office (S.O.)', 'Tanarada S.O', 'Aska Division'),
  ('761140', 'Dhumchai B.O', 'Branch Office (B.O.)', 'Tanarada S.O', 'Aska Division'),
  ('761140', 'Dihapadhala B.O', 'Branch Office (B.O.)', 'Tanarada S.O', 'Aska Division'),
  ('761140', 'G.Nuagam B.O', 'Branch Office (B.O.)', 'Tanarada S.O', 'Aska Division'),
  ('761140', 'Inginathi B.O', 'Branch Office (B.O.)', 'Tanarada S.O', 'Aska Division'),
  ('761140', 'K.Berhampur B.O', 'Branch Office (B.O.)', 'Tanarada S.O', 'Aska Division'),
  ('761140', 'Kanabhaga B.O', 'Branch Office (B.O.)', 'Tanarada S.O', 'Aska Division'),
  ('761140', 'Patulisahi B.O', 'Branch Office (B.O.)', 'Tanarada S.O', 'Aska Division'),
  ('761141', 'Gallery S.O', 'Sub Office (S.O.)', 'Gallery S.O', 'Aska Division'),
  ('761141', 'Badangi B.O', 'Branch Office (B.O.)', 'Gallery S.O', 'Aska Division'),
  ('761141', 'Domuhani B.O', 'Branch Office (B.O.)', 'Gallery S.O', 'Aska Division'),
  ('761141', 'Harigada B.O', 'Branch Office (B.O.)', 'Gallery S.O', 'Aska Division'),
  ('761141', 'Kupati B.O', 'Branch Office (B.O.)', 'Gallery S.O', 'Aska Division'),
  ('761143', 'Karachulli S.O', 'Sub Office (S.O.)', 'Karachulli S.O', 'Aska Division'),
  ('761143', 'B.Karadabadi B.O', 'Branch Office (B.O.)', 'Karachulli S.O', 'Aska Division'),
  ('761143', 'Biranchipur B.O', 'Branch Office (B.O.)', 'Karachulli S.O', 'Aska Division'),
  ('761143', 'Karasinghi B.O', 'Branch Office (B.O.)', 'Karachulli S.O', 'Aska Division'),
  ('761143', 'Takarada B.O', 'Branch Office (B.O.)', 'Karachulli S.O', 'Aska Division'),
  ('761144', 'Konkarada S.O', 'Sub Office (S.O.)', 'Konkarada S.O', 'Aska Division'),
  ('761144', 'Adapada B.O', 'Branch Office (B.O.)', 'Konkarada S.O', 'Aska Division'),
  ('761144', 'Dengadi B.O', 'Branch Office (B.O.)', 'Konkarada S.O', 'Aska Division'),
  ('761144', 'Kaudia B.O', 'Branch Office (B.O.)', 'Konkarada S.O', 'Aska Division'),
  ('761144', 'Kurla B.O', 'Branch Office (B.O.)', 'Konkarada S.O', 'Aska Division'),
  ('761146', 'Burupada S.O', 'Sub Office (S.O.)', 'Burupada S.O', 'Aska Division'),
  ('761146', 'Dengapadar B.O', 'Branch Office (B.O.)', 'Burupada S.O', 'Aska Division'),
  ('761146', 'Gobindapur B.O', 'Branch Office (B.O.)', 'Burupada S.O', 'Aska Division'),
  ('761146', 'Gothagam B.O', 'Branch Office (B.O.)', 'Burupada S.O', 'Aska Division'),
  ('761146', 'Thuruburai B.O', 'Branch Office (B.O.)', 'Burupada S.O', 'Aska Division'),
  ('761151', 'Asura Bandha S.O', 'Sub Office (S.O.)', 'Asura Bandha S.O', 'Aska Division'),
  ('761151', 'Badabaraba B.O', 'Branch Office (B.O.)', 'Asura Bandha S.O', 'Aska Division'),
  ('761151', 'Badagochha B.O', 'Branch Office (B.O.)', 'Asura Bandha S.O', 'Aska Division'),
  ('761151', 'Bhagabanpur B.O', 'Branch Office (B.O.)', 'Asura Bandha S.O', 'Aska Division'),
  ('761151', 'Gazalbadi B.O', 'Branch Office (B.O.)', 'Asura Bandha S.O', 'Aska Division'),
  ('761151', 'Ramanabadi B.O', 'Branch Office (B.O.)', 'Asura Bandha S.O', 'Aska Division'),
  ('761151', 'U. Dantilingi B.O', 'Branch Office (B.O.)', 'Asura Bandha S.O', 'Aska Division'),
  ('761209', 'Khariaguda S.O', 'Sub Office (S.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Bharampur B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Ch.Tikarapada B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Guma Dalaba B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Hukuma B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Kampa Khumbajhari B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Mandarada B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Narayanapur B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Puhundi B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'S.B.Jagadevpur B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Talapada B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Tinigharia B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division'),
  ('761209', 'Turubudi B.O', 'Branch Office (B.O.)', 'Khariaguda S.O', 'Berhampur Division')
ON CONFLICT (pincode, area_name) DO NOTHING;
