export const MASTER_KEYWORDS = {
  brand: ['BCR TRADERS', 'BCR traders online', 'BCR traders Odisha'],

  wholesale: [
    'wholesale commodities distributor Odisha',
    'wholesale grocery distributor India',
    'bulk food distributor Odisha',
    'wholesale food supplier near me',
    'best distributor Odisha',
    'commodity wholesale dealer',
    'FMCG distributor Odisha',
    'wholesale grocery online India',
    'bulk order grocery Odisha',
    'commercial food supplier India',
  ],

  oil: [
    'edible oil wholesale Odisha',
    'cooking oil distributor Odisha',
    'sunflower oil wholesale price',
    'mustard oil wholesale dealer India',
    'refined oil bulk supplier',
    'Fortune oil wholesale Odisha',
    'edible oil 5 litre wholesale',
    'best cooking oil dealer Odisha',
    'groundnut oil wholesale price India',
    'palm oil wholesale supplier',
    'soya bean oil bulk order',
    'cold pressed oil wholesale India',
  ],

  pulses: [
    'pulses wholesale Odisha',
    'dal distributor Odisha',
    'toor dal wholesale price',
    'moong dal bulk purchase',
    'chana dal wholesale dealer',
    'masoor dal distributor India',
    'urad dal wholesale Odisha',
    'pulses and lentils wholesale',
    'protein rich dal bulk order',
    'best dal dealer Odisha',
  ],

  atta: [
    'atta wholesale Odisha',
    'wheat flour bulk order India',
    'Aashirvaad atta wholesale price',
    'whole wheat atta distributor',
    'chakki atta wholesale dealer',
    'flour distributor Odisha',
    'maida wholesale price India',
    'besan wholesale supplier',
    'multigrain atta bulk purchase',
  ],

  spices: [
    'spices wholesale Odisha',
    'masala distributor Odisha',
    'turmeric powder wholesale price',
    'red chilli powder bulk order',
    'garam masala wholesale dealer',
    'coriander powder distributor',
    'cumin seeds wholesale India',
    'whole spices bulk supplier',
    'Indian spices wholesale market',
    'masala manufacturer dealer Odisha',
    'MDH spices wholesale price',
    'Everest masala wholesale Odisha',
  ],

  sugar: [
    'sugar wholesale Odisha',
    'refined sugar distributor India',
    'sugar bulk order price',
    'jaggery wholesale dealer Odisha',
    'sugar mill distributor',
    'Renuka sugar wholesale',
    'brown sugar wholesale India',
    'sugar supplier near me',
    'bulk sugar purchase Odisha',
  ],

  water: [
    'packaged water wholesale Odisha',
    'mineral water bottle bulk order',
    'water bottle distributor India',
    'Bisleri wholesale Odisha',
    'packaged drinking water supplier',
    '20 litre water can wholesale',
    'water bottle case price India',
    'bulk mineral water purchase',
  ],

  longTail: [
    'where to buy wholesale oil in Odisha',
    'best dal price in Odisha wholesale',
    'BCR traders oil price today',
    'wholesale grocery near me Odisha',
    'bulk order spices Odisha',
    'how to buy atta in bulk India',
    'commodity distributor Bhubaneswar',
    'wholesale market for pulses Odisha',
    'best wholesale sugar price India 2025',
    'oil pulses sugar wholesale online delivery Odisha',
  ],
}
